# vim: set noexpandtab:
#!/bin/bash

echo '# Automatically generated by build.sh' > lambda.coffee

cat preprocessor.coffee >>  lambda.coffee
cat functional.coffee   >>  lambda.coffee
cat boolean.coffee      >>  lambda.coffee
cat arithmetic.coffee   >>  lambda.coffee
cat list.coffee         >>  lambda.coffee
cat string.coffee       >>  lambda.coffee
cat stdlib.coffee       >>  lambda.coffee
cat optimizer.coffee    >>  lambda.coffee
cat meta.coffee         >>  lambda.coffee
cat test.coffee         >>  lambda.coffee

coffee -b -c lambda.coffee

tail -n+3 lambda.js > lambda2.js
node lambda2.js
